django_todo/urls.py
from django.conf.urls import url
from django.contrib import admin
from todo.views import say_hello, get_todo_list, get_test, create_an_item, edit_an_item, toggle_an_item

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', say_hello),
    url(r'^todo$', get_todo_list),
    url(r'^test$', get_test),
    url(r'^add$', create_an_item),
    url(r'^edit/(?P<id>\d+)$', edit_an_item),
    url(r'^toggle/(?P<id>\d+)$', toggle_an_item)
    
]

todo/models.py
from django.db import models

# Create your models here.
class Item(models.Model):
    name = models.CharField(max_length=30, blank=False)
    done = models.BooleanField(blank=False, default=False)

    def __str__(self):
        return self.name

todo/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item    
        fields = ('name', 'done')  # all the fields that we need

todo/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from .models import Item
from .forms import ItemForm

# Create your views here.
def say_hello(request):
    return HttpResponse("Hellow World")
    
def get_test(request):
    return render(request, "test.html")

def get_todo_list(request):
    results = Item.objects.all()
    # for x in results:
    #     print(x.name, x.done)
    return render(request, "todo_list.html", {"items": results})

# def create_an_item(request):
    
#     if request.method == "POST":
#         print(request.POST) 
#         new_item = Item()  # intance of the Item class created in models "EMPTY!"
#         new_item.name = request.POST.get("name")    # fetch from form
#         new_item.done = "done" in request.POST      # saves a true or false value in the database
#         new_item.save()
#         return redirect(get_todo_list)
        
#     return render(request, "item_form.html")


def create_an_item(request):
    
    if request.method == "POST":
        form = ItemForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect(get_todo_list)
    else:
        form = ItemForm()
        
    return render(request, "item_form.html", {'form':form})
    

def edit_an_item(request, id):
    item = get_object_or_404(Item, pk=id) # pk being the Primary Key
    
    if request.method == "POST":
        form = ItemForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return redirect(get_todo_list)
    else:
        form = ItemForm(instance=item)
    return render(request, "item_form.html", {'form':form})
    
    
def toggle_an_item(request, id):
    item = get_object_or_404(Item, pk=id) # pk being the Primary Key
    
    item.done = not item.done
    item.save()
    return redirect(get_todo_list)

    
    

todo/templates/item_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>I need to do this...</h1>
    <form method="POST">
        
        {% csrf_token %}
        
        
        {{ form.as_p }}
        
<!--        <label>Name: <input type="text" id="id_name" name="name"/>
        </label><br><br>
        
        <label>Done: <input type="checkbox" id="id_done" name="done"/>
        </label><br><br>-->

        <button type="submit">Submit</button>
        
    </form>
</body>
</html>

todo/templates/test.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
        .container {
            padding: 0 8rem;
        }
        h1 {
            text-align: center;
        }
    </style>
</head>

<body>
    <h1>TEST PAGE</h1>
    <div class="container">
        <p>this is just a template put in place to test django template creations!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste dolorum, eligendi? Culpa obcaecati asperiores sapiente, quae autem explicabo earum accusamus ipsum quis omnis iure ipsa ullam a corporis dolor aliquam labore error unde officiis veritatis
            rem enim? Debitis in adipisci perspiciatis praesentium fuga iste ea odit cum molestias temporibus, nostrum accusamus consequuntur et aperiam nobis repellat ipsum esse natus impedit facilis quam architecto quod atque. Magni fugiat dolorem ullam
            amet omnis officia dicta ab repellat suscipit laboriosam quisquam, recusandae distinctio quidem nulla accusamus enim fuga reiciendis eaque aut quis saepe soluta molestias laborum? Sint placeat facilis tempora soluta quia temporibus totam ex
            molestias distinctio ipsum! Libero animi architecto, distinctio facilis ullam vero nam laboriosam, debitis rem minima repudiandae accusamus ipsum at esse tenetur quaerat, commodi maxime quibusdam odio similique non. Molestiae ipsam voluptas
            dicta hic quis, fuga dolorem voluptate molestias eius, voluptatibus fugit cupiditate sequi eos ex quae tenetur, praesentium accusantium? Ratione dolorem in eum non aperiam quos minus eaque obcaecati velit esse totam, corporis rem. Unde laborum
            beatae deleniti, harum iure ullam fugit qui ipsa eius? Laudantium amet hic nam earum ab ducimus autem eaque repellendus, voluptates cum laboriosam! Nam neque officiis sequi ex natus rem laborum aperiam alias.</p>
    </div>
</body>

</html>

todo/templates/todo_list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Todo List</title>
</head>

<body>
    <h1>Things that need doing</h1>
    <table>

        {% for item in items %}
        <tr>
            {% if item.done %}
            <td><strike>{{ item.name }}</strike></td>
            {% else %}
            <td>{{ item.name }}</td>
            {% endif %}

            <td>
                <form method="POST" action="toggle/{{ item.id }}">{% csrf_token %}<input type="submit" value="Toggle">
                </form>
            </td>
            
            <td>
                <form method="GET" action="edit/{{ item.id }}"><input type="submit" value="Edit"></form>
            </td>
        </tr>
        {% empty %}
        <p>You have nothing to do.</p>
        {% endfor %}
    </table>

    <a href="add"> Add an item</a>

</body>

</html>